### ISSUE TITLE
Can't Proguard

### ISSUE THREAD

**Issue by kasim1011** [codinguser/android_contact_picker#11]
on generating Release APK
I get warning message

> Warning:com.codinguser.android.contactpicker.ContactsListFragment: can't find referenced field 'int action_search' in program class com.codinguser.android.contactpicker.R$id
> Warning:com.codinguser.android.contactpicker.ContactsListFragment: can't find referenced field 'int action_add_contact' in program class com.codinguser.android.contactpicker.R$id

**Comment by kasim1011** [comment]
In my case I've done with
`-dontwarn com.codinguser.android.contactpicker.**`

**Comment by codinguser** [comment]
I should probably put that in the README somewhere. Might solve some issues people are having with classes not found.
thanks

**Comment by kasim1011** [comment]
you're welcome. :+1:
