### ISSUE TITLE
Gradle Usage 

### ISSUE THREAD

**Issue by AmirHadifar** [codinguser/android_contact_picker#6]
Thanks in advance  
Please add your lib to to Gradle Repository

**Comment by codinguser** [comment]
Are there are specific benefits to this? The library is already in the
maven repository and gradle can access those easily.

**Comment by AmirHadifar** [comment]
Yeah now a day most of the developers use gradle so for those who want to
use your lib its easier to use :)

**Comment by ZBlaZe** [comment]
Warning:Packaging for dependency com.codinguser.android:contactpicker:2.2.0 is 'apklib' and is not supported. Only 'aar' libraries are supported.

**Comment by codinguser** [comment]
New version 3.0.0 now available in .aar format in the Maven central repository and can be used in Gradle easily.
